# Generated by Django 5.1.6 on 2025-03-19 13:57

import account_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadhar_card', models.CharField(max_length=12, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=12, unique=True)),
                ('account_number', models.BigIntegerField(default=account_app.models.generate_accountnumber, unique=True)),
                ('cif_number', models.BigIntegerField(default=account_app.models.generate_cifnumber, unique=True)),
            ],
        ),
    ]
