# Generated by Django 5.1.6 on 2025-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
