# Generated by Django 5.1.6 on 2025-03-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_userdetails_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='dob',
        ),
    ]
